
apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-application
   labels: 
     app: my-application
   spec:
   replicas: 2
   selector: 
      matchLabels:
         app: my-application
template:
 metadata:
   name: my-application
   labels:
     app: my-application
   spec: 
   containers:
     - name: My-container
       image: shrikant712/docker:latest
       ports:
         containerPort: 8080
